# Generated by Django 3.2 on 2022-05-25 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=255)),
                ('numPages', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BookItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barCode', models.CharField(max_length=255)),
                ('borrowed', models.DateField()),
                ('dueDate', models.DateField()),
                ('genre', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('publicationDate', models.CharField(max_length=255)),
            ],
        ),
    ]
