# Generated by Django 3.2 on 2022-05-23 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cod',
        ),
    ]
