# Generated by Django 3.2 on 2022-05-24 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barCode', models.CharField(max_length=255)),
                ('borrowed', models.DateField()),
                ('dueDate', models.DateField()),
                ('genre', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('publicationDate', models.CharField(max_length=255)),
            ],
        ),
    ]
